CREATE TABLE PRODUCT_DETAILS (
	PRODUCT_ID INT,
	PRODUCT_NAME VARCHAR(100),
	PRODUCT_CATEGORY VARCHAR(100),
	PRODUCT_PRICE INT
);

INSERT INTO PRODUCT_DETAILS VALUES (1,'Samsung S22', 'Mobile Phones', 1500);
INSERT INTO PRODUCT_DETAILS VALUES (2,'Samsung Tab S8+', 'Tablets', 1000);
INSERT INTO PRODUCT_DETAILS VALUES (3,'Nikon D7500', 'Cameras', 700);
INSERT INTO PRODUCT_DETAILS VALUES (4,'Samsung Crystal 4K', 'Televisions', 500);
INSERT INTO PRODUCT_DETAILS VALUES (5,'Yonex Badminton Racquet', 'Sports Accessories', 100);